export const PRODUCER_REPOSITORY = Symbol('PRODUCER_REPOSITORY');
export const FARM_REPOSITORY = Symbol('FARM_REPOSITORY');
export const HARVEST_REPOSITORY = Symbol('HARVEST_REPOSITORY');
export const CROP_REPOSITORY = Symbol('CROP_REPOSITORY');
export const PLANTING_REPOSITORY = Symbol('PLANTING_REPOSITORY');
